server:
  port:
  address: 0.0.0.0
spring:
  kafka:
    bootstrap-servers: "localhost:29092"
  data:
    mongodb:
      host: "localhost"
      port: 27017
      username: "root"
      password: "example"
      database: "cvizard"
      authentication-database: "admin"
gotenberg:
  api:
    url: "http://localhost:3000""g"