
name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  java_ci_with_maven:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
  docker_build_and_push:
       runs-on: ubuntu-latest
       needs: ["java_ci_with_maven"]
       steps:
       - name: Checkout code
         uses: actions/checkout@v3

       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v1

       - name: Login to Docker Registry
         uses: docker/login-action@v1
         with:
           registry: https://cvizard.com:5001
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}

       - name: Build and push
         uses: docker/build-push-action@v2
         with:
           context: .
           push: true
           tags: cvizard.com:5001/pdfmaker:${{ github.sha }}
           
  deploy:
      if: github.event.pull_request.merged == true
      runs-on: ubuntu-latest
      needs: ["docker_build_and_push"]
      steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: install ssh
        run: sudo apt-get install -y ssh
        
      - name: Login to Docker Registry
        uses: docker/login-action@v1
        with:
          registry: https://cvizard.com:5001
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker login cvizard.com:5001 -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            sed -i 's|cvizard.com:5001/pdfmaker:.*|cvizard.com:5001/pdfmaker:${{ github.sha }}|' CVizard/docker-compose.yml
            cd CVizard && docker compose stop pdfmaker && docker compose build pdfmaker && docker compose up -d pdfmaker
